name: Dev-Plan & Deploy

on:
  push:
    branches-ignore: ['main']
    paths:
      - 'terraform_stuff/**'
      - '!.github/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  Pre-Commit:
    name: Pre-Commit
    uses: ./aws_architecture_beginner/.github/workflows/run_pre_commit.yml@main

  Dev-Plan:
    name: Dev-Plan
    uses: ./aws_architecture_beginner/.github/workflows/plan_only.yml@main
    with:
      role-to-assume: arn:aws:iam::167339939270:role/adapt-github-actions-role
      environment: dev
    needs: Pre-Commit

  Dev-Deploy:
    name: Dev-Deploy
    if: github.event_name == 'workflow_dispatch'
    uses: ./aws_architecture_beginner/.github/workflows/deploy_infra.yml@main
    with:
      role-to-assume: arn:aws:iam::167339939270:role/adapt-github-actions-role
      environment: dev
      github_environment: dev
    needs: Dev-Plan
